// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Awardee {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  category?: string;
  role?: string;
  country?: string;
  year?: string;
  photo_url?: string;
  photo_position?: string;
  citation?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Edition {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  year: string;
  tag?: string;
  location?: string;
  venue?: string;
  date?: string;
  intro?: string;
  image_url?: string;
  summary?: PortableTextBlock[];
  upcoming?: boolean;
  stats?: { "v": string; "l": string }[];
  team?: { "role": string; "name": string }[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface GalleryPhoto {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  image_url: string;
  album?: string;
  span?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Programme {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  number?: string;
  label?: string;
  excerpt?: string;
  image_url?: string;
  link?: string;
  overview?: PortableTextBlock[];
  details?: { "key": string; "value": string }[];
  offers?: { "icon"?: string | null; "title": string; "body"?: string | null }[];
  moments?: { "image_url": string }[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    awardees: Awardee;
    editions: Edition;
    gallery_photos: GalleryPhoto;
    programmes: Programme;
  }
}